sonar.projectKey=vkit
sonar.projectName=vkit
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/dist/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
